#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see trovestack functions_qemu

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get --allow-unauthenticated -y install \
    libxml2-dev libxslt1-dev libffi-dev libssl-dev libyaml-dev \
    python3-pip python3-sqlalchemy python3-setuptools

# Install python 3.7, some python lib (e.g. oslo.concurrency>4.0.0) requries
# Python 3.7
add-apt-repository --yes ppa:deadsnakes/ppa
apt update
apt install -y python3.7 python3.7-dev

update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 10
python3.5 -m pip install pip==9.0.3
python3.5 -m pip install -U wheel setuptools

TMP_HOOKS_DIR="/tmp/in_target.d"

UPPER_CONSTRAINTS=
if [ -f ${TMP_HOOKS_DIR}/upper-constraints.txt ]; then
    UPPER_CONSTRAINTS=" -c ${TMP_HOOKS_DIR}/upper-constraints.txt"
fi

python3.7 -m pip install pip==9.0.3
python3.7 -m pip install -U wheel setuptools
python3.7 -m pip install --upgrade -r ${TMP_HOOKS_DIR}/requirements.txt ${UPPER_CONSTRAINTS}

echo "diagnostic pip freeze output follows"
python3.7 -m pip freeze
echo "diagnostic pip freeze output above"
