#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y purge acpid\
                 apport\
                 apport-symptoms\
                 apt-transport-https\
                 apt-xapian-index\
                 aptitude\
                 at\
                 bash-completion\
                 bc\
                 bind9-host\
                 bsdmainutils\
                 busybox-static\
                 byobu\
                 command-not-found\
                 command-not-found-data\
                 curl\
                 dbus\
                 dmidecode\
                 dosfstools\
                 ed\
                 fonts-ubuntu-font-family-console\
                 friendly-recovery\
                 ftp\
                 fuse\
                 geoip-database\
                 groff-base\
                 hdparm\
                 info\
                 install-info\
                 iptables\
                 iputils-tracepath\
                 irqbalance\
                 landscape-client\
                 landscape-common\
                 language-selector-common\
                 laptop-detect\
                 libaccountsservice0\
                 libbind9-90\
                 libclass-accessor-perl\
                 libcwidget3\
                 libdns100\
                 libept1.4.12\
                 libevent-2.0-5\
                 libgc1c2\
                 libgeoip1\
                 libio-string-perl\
                 libisc95\
                 liblwres90\
                 libnfnetlink0\
                 libparse-debianchangelog-perl\
                 libparted0debian1\
                 libpcap0.8\
                 libpci3\
                 libpipeline1\
                 libpolkit-gobject-1-0\
                 libsasl2-modules\
                 libsigc++-2.0-0c2a\
                 libsub-name-perl\
                 libusb-1.0-0\
                 libxapian22\
                 lshw\
                 lsof\
                 ltrace\
                 man-db\
                 mlocate\
                 mtr-tiny\
                 nano\
                 ntfs-3g\
                 parted\
                 patch\
                 plymouth-theme-ubuntu-text\
                 popularity-contest\
                 powermgmt-base\
                 ppp\
                 pppoeconf\
                 python-debian\
                 python-gdbm\
                 python-pam\
                 python-twisted-bin\
                 python-xapian\
                 python-zope.interface\
                 screen\
                 shared-mime-info\
                 strace\
                 tasksel\
                 tcpdump\
                 telnet\
                 time\
                 tmux\
                 ubuntu-standard\
                 ufw\
                 update-manager-core\
                 update-notifier-common\
                 usbutils\
                 uuid-runtime\
                 w3m

# The following packages cannot be removed as they cause cloud-init to be
# uninstalled in Ubuntu 14.04
#                 gir1.2-glib-2.0
#                 libdbus-glib-1-2
#                 libgirepository-1.0-1
#                 python-chardet
#                 python-serial
#                 xz-utils

apt-get -y autoremove

