#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get --allow-unauthenticated install -qy curl
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
apt-get update
apt-get --allow-unauthenticated install -qy openjdk-7-jdk expect python-dev
apt-get --allow-unauthenticated install -qy libxml2-dev ntp mc
apt-get --allow-unauthenticated install -qy libxslt1-dev python-pexpect
apt-get --allow-unauthenticated install -qy python-migrate build-essential

apt-get --allow-unauthenticated install dsc21=2.1.* cassandra=2.1.* -qy

# The Python Driver 2.0 for Apache Cassandra.
pip2 install cassandra-driver
# Sorted sets support for the Python driver.
pip2 install blist

service cassandra stop
rm -rf /var/lib/cassandra/data/system/*
service cassandra start
