#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "$DIB_INIT_SYSTEM" == "systemd" ]; then
    systemctl enable $(svc-map guest-agent docker-hostnic.socket)
fi

if [[ ${SYNC_LOG_TO_CONTROLLER} == "True" ]]; then
    systemctl enable guest-log-collection.timer
fi