#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: take "staged" trove-guest.conf file and put it in the init directory on guest image

dd if=/tmp/in_target.d/trove-guest.service of=/etc/systemd/system/trove-guest.service

systemctl enable trove-guest.service


