#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: configure trove-guest service to use system store of trusted certificates

GUEST_UNIT_DROPINS="/etc/systemd/system/trove-guest.service.d"

mkdir -v -p ${GUEST_UNIT_DROPINS}
cat <<EOF > ${GUEST_UNIT_DROPINS}/30-use-system-certificates.conf
[Service]
Environment=REQUESTS_CA_BUNDLE=/etc/ssl/certs
EOF
