#!/bin/bash

set -e
set -o xtrace

[ -n "${RELEASE}" ] || die "RELEASE must be set to either trusty or xenial"

apt-get --allow-unauthenticated -y install software-properties-common

get_key_robust EA312927

echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

apt-get -y update
