#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y purge acpid\
                 apport\
                 apport-symptoms\
                 apt-transport-https\
                 aptitude\
                 at\
                 bash-completion\
                 bc\
                 bind9-host\
                 bsdmainutils\
                 busybox-static\
                 byobu\
                 command-not-found\
                 command-not-found-data\
                 curl\
                 dbus\
                 dmidecode\
                 dosfstools\
                 ed\
                 fonts-ubuntu-font-family-console\
                 friendly-recovery\
                 ftp\
                 fuse\
                 geoip-database\
                 groff-base\
                 hdparm\
                 info\
                 install-info\
                 iptables\
                 iputils-tracepath\
                 irqbalance\
                 language-selector-common\
                 libaccountsservice0\
                 libevent-2.0-5\
                 libgeoip1\
                 libnfnetlink0\
                 libpcap0.8\
                 libpci3\
                 libpipeline1\
                 libpolkit-gobject-1-0\
                 libsasl2-modules\
                 libusb-1.0-0\
                 lshw\
                 lsof\
                 ltrace\
                 man-db\
                 mlocate\
                 mtr-tiny\
                 nano\
                 ntfs-3g\
                 parted\
                 patch\
                 plymouth-theme-ubuntu-text\
                 popularity-contest\
                 powermgmt-base\
                 ppp\
                 screen\
                 shared-mime-info\
                 strace\
                 tcpdump\
                 telnet\
                 time\
                 tmux\
                 ubuntu-standard\
                 ufw\
                 update-manager-core\
                 update-notifier-common\
                 usbutils\
                 uuid-runtime\

# The following packages cannot be removed as they cause cloud-init to be
# uninstalled in Ubuntu 14.04
#                 gir1.2-glib-2.0
#                 libdbus-glib-1-2
#                 libgirepository-1.0-1
#                 python-chardet
#                 python-serial
#                 xz-utils

apt-get -y autoremove

