#!/bin/bash

set -e
set -o xtrace

# The HWE stack must be installed for nested virtualization on ppc64el.  This
# environment variable is set automatically by trovestack, but it may also be
# set by the user when manually invoking disk-image-create.

case "$DIB_USE_HWE_KERNEL" in
    true|True|TRUE|yes|Yes|YES)
        DIB_USE_HWE_KERNEL=true
        ;;
    *)
        DIB_USE_HWE_KERNEL=false
        ;;
esac

if [ "$DIB_USE_HWE_KERNEL" == "true" ]; then
    export DEBIAN_FRONTEND=noninteractive

    PKG_ARCH=$(dpkg --print-architecture)

    case "$PKG_ARCH" in
        amd64|arm64|ppc64el|s390x)
            apt-get --allow-unauthenticated install -y linux-generic-hwe-16.04
            ;;
    esac
fi
